const STORAGE_KEY="sakura-day-tasks-v1",THEME_KEY="sakura-day-theme";
const pad=n=>String(n).padStart(2,"0"),toDateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const fromDateKey=k=>{const[y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d)},addDays=(d,n)=>{const c=new Date(d);c.setDate(c.getDate()+n);return c};
const today=new Date();today.setHours(0,0,0,0);const todayKey=toDateKey(today);
const categoryConfig={"Học tập":{color:"#9b80e5",icon:"📚"},"Công việc":{color:"#6baeea",icon:"💻"},"Cá nhân":{color:"#f27da7",icon:"🌸"},"Sức khỏe":{color:"#5fc5a5",icon:"🍵"}};
const starterTasks=[
 {id:crypto.randomUUID(),title:"Hoàn thiện giao diện dự án",date:todayKey,time:"09:00",category:"Công việc",priority:"high",notes:"Kiểm tra responsive trên điện thoại",completed:false,createdAt:Date.now()},
 {id:crypto.randomUUID(),title:"Ôn 20 từ vựng tiếng Nhật",date:todayKey,time:"14:30",category:"Học tập",priority:"normal",notes:"",completed:false,createdAt:Date.now()+1},
 {id:crypto.randomUUID(),title:"Đi bộ thư giãn 30 phút",date:toDateKey(addDays(today,1)),time:"18:00",category:"Sức khỏe",priority:"normal",notes:"",completed:false,createdAt:Date.now()+2},
 {id:crypto.randomUUID(),title:"Gọi điện cho gia đình",date:toDateKey(addDays(today,2)),time:"20:00",category:"Cá nhân",priority:"high",notes:"",completed:false,createdAt:Date.now()+3},
 {id:crypto.randomUUID(),title:"Đọc xong chương 4",date:toDateKey(addDays(today,-1)),time:"21:00",category:"Học tập",priority:"normal",notes:"",completed:true,createdAt:Date.now()+4}
];
let tasks=loadTasks();
let state={filter:"all",view:"pending",search:"",sortAsc:true,calendarDate:new Date(today.getFullYear(),today.getMonth(),1),selectedDate:todayKey,pendingDeleteId:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const elements={taskList:$("#taskList"),emptyState:$("#emptyState"),taskModal:$("#taskModal"),taskForm:$("#taskForm"),confirmModal:$("#confirmModal"),calendarGrid:$("#calendarGrid"),calendarTitle:$("#calendarTitle"),miniSchedule:$("#miniSchedule"),selectedDateTitle:$("#selectedDateTitle"),searchInput:$("#searchInput"),pageTitle:$("#pageTitle"),progressRing:$("#progressRing"),progressPercent:$("#progressPercent"),progressMessage:$("#progressMessage"),progressDetail:$("#progressDetail"),categoryList:$("#categoryList"),quickDateInput:$("#quickDateInput"),quickDateLabel:$("#quickDateLabel"),toast:$("#toast")};

function loadTasks(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(saved)?saved:starterTasks}catch{return starterTasks}}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(tasks))}
function formatDate(key,options={day:"2-digit",month:"2-digit"}){return new Intl.DateTimeFormat("vi-VN",options).format(fromDateKey(key))}
function escapeHtml(value=""){return value.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
function render(){renderTasks();renderCalendar();renderSchedule();renderCounts();renderCategories();renderProgress()}
function getVisibleTasks(){let result=tasks.filter(t=>state.view==="completed"?t.completed:!t.completed);if(state.filter==="today")result=result.filter(t=>t.date===todayKey);if(state.filter==="upcoming")result=result.filter(t=>t.date>todayKey&&!t.completed);if(state.filter==="important")result=result.filter(t=>t.priority==="high");if(state.filter==="completed")result=tasks.filter(t=>t.completed);if(state.search){const q=state.search.toLocaleLowerCase("vi");result=result.filter(t=>`${t.title} ${t.category} ${t.notes}`.toLocaleLowerCase("vi").includes(q))}return result.sort((a,b)=>{const first=`${a.date} ${a.time||"23:59"}`,second=`${b.date} ${b.time||"23:59"}`;return state.sortAsc?first.localeCompare(second):second.localeCompare(first)})}
function renderTasks(){const visible=getVisibleTasks();elements.emptyState.hidden=visible.length>0;elements.taskList.innerHTML=visible.map((task,index)=>{const config=categoryConfig[task.category]||categoryConfig["Cá nhân"],overdue=!task.completed&&task.date<todayKey,dateLabel=task.date===todayKey?"Hôm nay":formatDate(task.date,{weekday:"short",day:"2-digit",month:"2-digit"});return `<article class="task-card ${task.completed?"completed":""}" style="--category-color:${config.color};animation-delay:${Math.min(index*35,245)}ms" data-id="${task.id}"><button class="task-check" data-action="toggle" aria-label="${task.completed?"Đánh dấu chưa xong":"Hoàn thành"}"><span>✓</span></button><div class="task-main"><span class="task-title" title="${escapeHtml(task.title)}">${escapeHtml(task.title)}</span><div class="task-meta"><span class="${overdue?"overdue":""}">▣ ${overdue?"Quá hạn · ":""}${dateLabel}</span>${task.time?`<span>◷ ${task.time}</span>`:""}<span class="category-chip">${config.icon} ${escapeHtml(task.category)}</span></div></div><div class="task-actions"><button class="star ${task.priority==="high"?"active":""}" data-action="star" aria-label="Quan trọng">${task.priority==="high"?"★":"☆"}</button><button class="edit" data-action="edit" aria-label="Sửa">✎</button><button class="delete" data-action="delete" aria-label="Xóa">⌫</button></div></article>`}).join("")}
function renderCalendar(){const year=state.calendarDate.getFullYear(),month=state.calendarDate.getMonth();elements.calendarTitle.textContent=new Intl.DateTimeFormat("vi-VN",{month:"long",year:"numeric"}).format(state.calendarDate);const monthStart=new Date(year,month,1),offset=(monthStart.getDay()+6)%7,gridStart=addDays(monthStart,-offset),days=[];for(let i=0;i<42;i++){const date=addDays(gridStart,i),key=toDateKey(date),dayTasks=tasks.filter(t=>t.date===key),dotCount=Math.min(dayTasks.length,3);days.push(`<button class="calendar-day ${date.getMonth()!==month?"other":""} ${key===todayKey?"today":""} ${key===state.selectedDate?"selected":""}" data-date="${key}" aria-label="${formatDate(key,{day:"numeric",month:"long",year:"numeric"})}">${date.getDate()}${dotCount?`<span class="dots">${"<i></i>".repeat(dotCount)}</span>`:""}</button>`)}elements.calendarGrid.innerHTML=days.join("")}
function renderSchedule(){const date=fromDateKey(state.selectedDate);elements.selectedDateTitle.textContent=state.selectedDate===todayKey?"Hôm nay":new Intl.DateTimeFormat("vi-VN",{weekday:"long",day:"numeric",month:"long"}).format(date);const dayTasks=tasks.filter(t=>t.date===state.selectedDate).sort((a,b)=>(a.time||"99:99").localeCompare(b.time||"99:99"));if(!dayTasks.length){elements.miniSchedule.innerHTML=`<div class="schedule-empty"><b>☁</b>Ngày này chưa có lịch trình.<br>Hãy dành thời gian cho bản thân nhé!</div>`;return}elements.miniSchedule.innerHTML=dayTasks.slice(0,5).map(task=>{const config=categoryConfig[task.category]||categoryConfig["Cá nhân"];return `<div class="schedule-item"><span class="schedule-time">${task.time||"Cả ngày"}</span><i class="schedule-line" style="--item-color:${config.color}"></i><div class="schedule-copy"><strong>${task.completed?"✓ ":""}${escapeHtml(task.title)}</strong><span>${config.icon} ${escapeHtml(task.category)}</span></div></div>`}).join("")}
function renderCounts(){$("#countAll").textContent=tasks.filter(t=>!t.completed).length;$("#countToday").textContent=tasks.filter(t=>t.date===todayKey&&!t.completed).length;$("#countUpcoming").textContent=tasks.filter(t=>t.date>todayKey&&!t.completed).length;$("#countImportant").textContent=tasks.filter(t=>t.priority==="high"&&!t.completed).length;$("#countCompleted").textContent=tasks.filter(t=>t.completed).length}
function renderCategories(){elements.categoryList.innerHTML=Object.entries(categoryConfig).map(([name,config])=>`<div class="category-item"><i style="background:${config.color}"></i><span>${name}</span><b>${tasks.filter(t=>t.category===name&&!t.completed).length}</b></div>`).join("")}
function renderProgress(){const todayTasks=tasks.filter(t=>t.date===todayKey),done=todayTasks.filter(t=>t.completed).length,percent=todayTasks.length?Math.round(done/todayTasks.length*100):0;elements.progressRing.style.setProperty("--progress",percent);elements.progressPercent.textContent=`${percent}%`;if(percent===100&&todayTasks.length){elements.progressMessage.textContent="Tuyệt vời, hoàn thành rồi!";elements.progressDetail.textContent="Bạn đã chinh phục mọi nhiệm vụ hôm nay ✨"}else{elements.progressMessage.textContent=percent>=50?"Bạn đang làm rất tốt!":"Ngày mới tuyệt vời!";elements.progressDetail.textContent=todayTasks.length?`Đã xong ${done}/${todayTasks.length} nhiệm vụ hôm nay.`:"Hãy thêm một mục tiêu nhỏ cho hôm nay nhé."}}
function openTaskModal(task=null,date=null){$("#taskId").value=task?.id||"";$("#taskTitle").value=task?.title||"";$("#taskDate").value=task?.date||date||state.selectedDate||todayKey;$("#taskTime").value=task?.time||"";$("#taskCategory").value=task?.category||"Cá nhân";$("#taskPriority").value=task?.priority||"normal";$("#taskNotes").value=task?.notes||"";$("#modalTitle").textContent=task?"Chỉnh sửa nhiệm vụ ✎":"Thêm nhiệm vụ ✨";elements.taskModal.showModal();setTimeout(()=>$("#taskTitle").focus(),50)}
function closeTaskModal(){elements.taskModal.close()}
function saveTask(event){event.preventDefault();const id=$("#taskId").value,payload={title:$("#taskTitle").value.trim(),date:$("#taskDate").value,time:$("#taskTime").value,category:$("#taskCategory").value,priority:$("#taskPriority").value,notes:$("#taskNotes").value.trim()};if(!payload.title||!payload.date)return;if(id){tasks=tasks.map(t=>t.id===id?{...t,...payload}:t);showToast("Đã cập nhật nhiệm vụ!")}else{tasks.push({id:crypto.randomUUID(),...payload,completed:false,createdAt:Date.now()});showToast("Đã thêm nhiệm vụ mới!")}state.selectedDate=payload.date;const picked=fromDateKey(payload.date);state.calendarDate=new Date(picked.getFullYear(),picked.getMonth(),1);persist();closeTaskModal();render()}
function handleTaskAction(event){const button=event.target.closest("[data-action]"),card=event.target.closest(".task-card");if(!button||!card)return;const task=tasks.find(t=>t.id===card.dataset.id);if(!task)return;const action=button.dataset.action;if(action==="toggle"){task.completed=!task.completed;persist();if(task.completed){burstConfetti(button);showToast("Yay! Hoàn thành một nhiệm vụ ✨")}render()}if(action==="star"){task.priority=task.priority==="high"?"normal":"high";persist();render()}if(action==="edit")openTaskModal(task);if(action==="delete"){state.pendingDeleteId=task.id;elements.confirmModal.showModal()}}
function deletePendingTask(){if(!state.pendingDeleteId)return;tasks=tasks.filter(t=>t.id!==state.pendingDeleteId);state.pendingDeleteId=null;persist();elements.confirmModal.close();render();showToast("Đã xóa nhiệm vụ.")}
function showToast(message){elements.toast.querySelector("p").textContent=message;elements.toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>elements.toast.classList.remove("show"),2400)}
function burstConfetti(origin){const rect=origin.getBoundingClientRect(),colors=["#ff78a9","#9b80e5","#6ed4b6","#f5c768","#74baf6"],container=$("#confetti");for(let i=0;i<22;i++){const piece=document.createElement("i");piece.style.left=`${rect.left+rect.width/2}px`;piece.style.top=`${rect.top}px`;piece.style.background=colors[i%colors.length];piece.style.setProperty("--x",`${(Math.random()-.5)*80}px`);piece.style.setProperty("--y",`${(Math.random()-.5)*30}px`);piece.style.setProperty("--drift",`${(Math.random()-.5)*150}px`);piece.style.animationDelay=`${Math.random()*.12}s`;container.appendChild(piece);setTimeout(()=>piece.remove(),1200)}}
function setFilter(filter,label){state.filter=filter;if(filter==="completed")state.view="completed";else if(state.view==="completed")state.view="pending";$$('.nav-item').forEach(b=>b.classList.toggle("active",b.dataset.filter===filter));$$("#viewTabs button").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view));elements.pageTitle.innerHTML=`${label} <span>✿</span>`;renderTasks();closeSidebar()}
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem(THEME_KEY,theme);$("#themeMenu").classList.remove("open");showToast(`Đã chuyển sang giao diện ${theme==="pink"?"Sakura":theme==="light"?"trắng":"đen"}.`)}
function closeSidebar(){$("#sidebar").classList.remove("open");$("#sidebarOverlay").classList.remove("open")}
function initDateGreeting(){const hour=new Date().getHours(),greeting=hour<11?"Chào buổi sáng":hour<18?"Chào buổi chiều":"Chào buổi tối";$("#dateGreeting").textContent=`${greeting} · ${new Intl.DateTimeFormat("vi-VN",{weekday:"long",day:"numeric",month:"long"}).format(today)}`}
function bindEvents(){
 $("#openAddModal").addEventListener("click",()=>openTaskModal(null,todayKey));$("#emptyAddButton").addEventListener("click",()=>openTaskModal(null,todayKey));$("#addForSelectedDate").addEventListener("click",()=>openTaskModal(null,state.selectedDate));$("#closeModal").addEventListener("click",closeTaskModal);$("#cancelModal").addEventListener("click",closeTaskModal);elements.taskForm.addEventListener("submit",saveTask);elements.taskList.addEventListener("click",handleTaskAction);$("#cancelDelete").addEventListener("click",()=>{state.pendingDeleteId=null;elements.confirmModal.close()});$("#confirmDelete").addEventListener("click",deletePendingTask);
 $("#quickAddForm").addEventListener("submit",event=>{event.preventDefault();const input=$("#quickAddInput"),title=input.value.trim();if(!title)return;const date=elements.quickDateInput.value||todayKey;tasks.push({id:crypto.randomUUID(),title,date,time:"",category:"Cá nhân",priority:"normal",notes:"",completed:false,createdAt:Date.now()});input.value="";persist();render();showToast("Đã thêm nhanh nhiệm vụ!")});$("#quickDateButton").addEventListener("click",()=>{if(typeof elements.quickDateInput.showPicker==="function")elements.quickDateInput.showPicker();else elements.quickDateInput.click()});elements.quickDateInput.addEventListener("change",()=>{elements.quickDateLabel.textContent=elements.quickDateInput.value===todayKey?"Hôm nay":formatDate(elements.quickDateInput.value)});
 $$(".nav-item").forEach(button=>button.addEventListener("click",()=>setFilter(button.dataset.filter,button.querySelector("span:nth-child(2)").textContent)));$$("#viewTabs button").forEach(button=>button.addEventListener("click",()=>{state.view=button.dataset.view;if(state.view==="completed")state.filter="completed";else if(state.filter==="completed")state.filter="all";$$("#viewTabs button").forEach(item=>item.classList.toggle("active",item===button));$$(".nav-item").forEach(item=>item.classList.toggle("active",item.dataset.filter===state.filter));renderTasks()}));elements.searchInput.addEventListener("input",event=>{state.search=event.target.value.trim();renderTasks()});$("#sortButton").addEventListener("click",()=>{state.sortAsc=!state.sortAsc;$("#sortButton span").textContent=state.sortAsc?"Ngày gần nhất":"Ngày xa nhất";renderTasks()});
 elements.calendarGrid.addEventListener("click",event=>{const day=event.target.closest(".calendar-day");if(!day)return;state.selectedDate=day.dataset.date;const picked=fromDateKey(state.selectedDate);if(picked.getMonth()!==state.calendarDate.getMonth())state.calendarDate=new Date(picked.getFullYear(),picked.getMonth(),1);renderCalendar();renderSchedule()});$("#prevMonth").addEventListener("click",()=>{state.calendarDate.setMonth(state.calendarDate.getMonth()-1);state.calendarDate=new Date(state.calendarDate);renderCalendar()});$("#nextMonth").addEventListener("click",()=>{state.calendarDate.setMonth(state.calendarDate.getMonth()+1);state.calendarDate=new Date(state.calendarDate);renderCalendar()});$("#todayMonth").addEventListener("click",()=>{state.calendarDate=new Date(today.getFullYear(),today.getMonth(),1);state.selectedDate=todayKey;renderCalendar();renderSchedule()});
 $("#themeButton").addEventListener("click",event=>{event.stopPropagation();$("#themeMenu").classList.toggle("open")});$$("[data-theme-value]").forEach(button=>button.addEventListener("click",()=>setTheme(button.dataset.themeValue)));document.addEventListener("click",event=>{if(!event.target.closest("#themeSwitcher"))$("#themeMenu").classList.remove("open")});$("#openSidebar").addEventListener("click",()=>{$("#sidebar").classList.add("open");$("#sidebarOverlay").classList.add("open")});$("#closeSidebar").addEventListener("click",closeSidebar);$("#sidebarOverlay").addEventListener("click",closeSidebar);document.addEventListener("keydown",event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();elements.searchInput.focus()}if(event.key==="Escape")$("#themeMenu").classList.remove("open")});elements.taskModal.addEventListener("click",event=>{if(event.target===elements.taskModal)closeTaskModal()});elements.confirmModal.addEventListener("click",event=>{if(event.target===elements.confirmModal)elements.confirmModal.close()})
 $("#notificationButton").addEventListener("click",()=>{const due=tasks.filter(t=>t.date===todayKey&&!t.completed).length;showToast(due?`Bạn còn ${due} nhiệm vụ trong hôm nay 🌸`:"Hôm nay không còn việc cần làm!")});$("#manageCategories").addEventListener("click",()=>showToast("Bạn có thể chọn 4 danh mục khi tạo nhiệm vụ."));
}
function init(){document.documentElement.dataset.theme=localStorage.getItem(THEME_KEY)||"pink";elements.quickDateInput.value=todayKey;initDateGreeting();bindEvents();render()}
init();
